# -*- coding: utf-8 -*-
"""pizza.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iHc8rrdYj6kBXiDrjRJUMqiBwL6AgGZD

# **Main**
"""

import csv
import datetime
menu= "Lütfen Bir Pizza Tabanı Seçiniz: \n Klasik: 40 TL\n Margarita: 60TL \n Türk Pizza: 30TL \n Sade pizza: 20TL \nİstediğiniz soslar: \n Zeytin: 10TL \n Mantar: 10TL \n Keçi Peyniri: 15TL \n Et: 20TL \n Soğan: 10TL \n Mısır: 5TL"
menu_txt = open ("menu", "w")
menu_txt.write(menu) 

klasik = 40
margarita = 60
türk = 30
sade = 20

zeytin = 10
mantar = 10
keçipeyniri = 15
et = 20
soğan = 10
mısır = 5

tabanlar =[klasik, margarita, türk, sade]
soslar = [zeytin, mantar, keçipeyniri, et, soğan, mısır]
def main():
  print("""  ========Python Pizza=======[-][o][x]
  |                                 |
  |     Pizzacıya Hoşgeldiniz!      |
  |  Menüyü görmek için "x"e basın  |
  |Bir taban ve sos seçin ve sipariş|
  |bilgilerini de girince her şey   |
  |hazır! (tek sos ve tek taban)    |
  |=================================|""")
  x = input()
  if x == "x":
    print(menu)
    print("\nSeçiminizi yaptıysanız, ilerlemek için x'e basın")
  x = input()
  if x == "x":
    tabanistegi = input("Pizza tabanına ne istersiniz?")
    sosistegi = input("Peki ya sos? ")
    class Pizza():
      def __init__(self,taban,sos):
        self.taban = taban
        self.sos = sos   
      def get_description(self):
        print (f"Bu pizzanın tabanı: {tabanistegi} \nBu pizzanın sosu: {sosistegi} \nLezziz!")
      def get_cost(self):
          if (tabanistegi,sosistegi) == ("margarita","zeytin"):
            print (f"Pizzanızın fiyatı {margarita+zeytin} liradır.")
          elif (tabanistegi,sosistegi) == ("margarita","mantar"):
            print (f"Pizzanızın fiyatı {margarita+mantar} liradır.")
          elif (tabanistegi,sosistegi) == ("margarita","keçi peyniri"):
            print (f"Pizzanızın fiyatı {margarita+keçipeyniri} liradır.")
          elif (tabanistegi,sosistegi) == ("margarita","et"):
            print (f"Pizzanızın fiyatı {margarita+et} liradır.")
          elif (tabanistegi,sosistegi) == ("margarita","soğan"):
            print (f"Pizzanızın fiyatı {margarita+soğan} liradır.")
          elif (tabanistegi,sosistegi) == ("margarita","soğan"):
            print (f"Pizzanızın fiyatı {margarita+soğan} liradır.")
          elif (tabanistegi,sosistegi) == ("margarita","mısır"):
            print (f"Pizzanızın fiyatı {margarita+mısır} liradır.")

          elif (tabanistegi,sosistegi) == ("klasik","zeytin"):
            print (f"Pizzanızın fiyatı {klasik+zeytin} liradır.")
          elif (tabanistegi,sosistegi) == ("klasik","mantar"):
            print (f"Pizzanızın fiyatı {klasik+mantar} liradır.")
          elif (tabanistegi,sosistegi) == ("klasik","keçi peyniri"):
            print (f"Pizzanızın fiyatı {klasik+keçipeyniri} liradır.")
          elif (tabanistegi,sosistegi) == ("klasik","et"):
            print (f"Pizzanızın fiyatı {klasik+et} liradır.")
          elif (tabanistegi,sosistegi) == ("klasik","soğan"):
            print (f"Pizzanızın fiyatı {klasik+soğan} liradır.")
          elif (tabanistegi,sosistegi) == ("klasik","soğan"):
            print (f"Pizzanızın fiyatı {klasik+soğan} liradır.")
          elif (tabanistegi,sosistegi) == ("klasik","mısır"):
            print (f"Pizzanızın fiyatı {klasik+mısır} liradır.")

          elif (tabanistegi,sosistegi) == ("türk pizza","zeytin"):
            print (f"Pizzanızın fiyatı {türk+zeytin} liradır.")
          elif (tabanistegi,sosistegi) == ("türk pizza","mantar"):
            print (f"Pizzanızın fiyatı {türk+mantar} liradır.")
          elif (tabanistegi,sosistegi) == ("türk pizza","keçi peyniri"):
            print (f"Pizzanızın fiyatı {türk+keçipeyniri} liradır.")
          elif (tabanistegi,sosistegi) == ("türk pizza","et"):
            print (f"Pizzanızın fiyatı {türk+et} liradır.")
          elif (tabanistegi,sosistegi) == ("türk pizza","soğan"):
            print (f"Pizzanızın fiyatı {türk+soğan} liradır.")
          elif (tabanistegi,sosistegi) == ("türk pizza","soğan"):
            print (f"Pizzanızın fiyatı {türk+soğan} liradır.")
          elif (tabanistegi,sosistegi) == ("türk pizza","mısır"):
            print (f"Pizzanızın fiyatı {türk+mısır} liradır.")

          elif (tabanistegi,sosistegi) == ("sade pizza","zeytin"):
            print (f"Pizzanızın fiyatı {sade+zeytin} liradır.")
          elif (tabanistegi,sosistegi) == ("sade pizza","mantar"):
            print (f"Pizzanızın fiyatı {sade+mantar} liradır.")
          elif (tabanistegi,sosistegi) == ("sade pizza","keçi peyniri"):
            print (f"Pizzanızın fiyatı {sade+keçipeyniri} liradır.")
          elif (tabanistegi,sosistegi) == ("sade pizza","et"):
            print (f"Pizzanızın fiyatı {sade+et} liradır.")
          elif (tabanistegi,sosistegi) == ("sade pizza","soğan"):
            print (f"Pizzanızın fiyatı {sade+soğan} liradır.")
          elif (tabanistegi,sosistegi) == ("sade pizza","soğan"):
            print (f"Pizzanızın fiyatı {sade+soğan } liradır.")
          elif (tabanistegi,sosistegi) == ("sade pizza","mısır"):
            print (f"Pizzanızın fiyatı {sade+mısır} liradır.")
          else:
            print("Ne yazık ki henüz böyle bir pizzayı pişirebilecek teknolojimiz yok...\nLütfen menüde var olan iki malzemeden seçiniz!")
      

    pizza = Pizza((tabanistegi),(sosistegi))

    def Decorator():
        pizza.get_description()
        pizza.get_cost()

    Decorator()
  else: print("x'e basın!")
  print("İşlemleri tamamlamak için birkaç adım daha kaldı...")
  ad = input("Adınız nedir?  " )
  tckimlik = input("TC kimlik?  ")
  kart = input("Kredi kartı numaranız?  ")
  kartşifre = input("Kredi kartı şifreniz?  ")
  zaman = input("Ne zamana sipariş vermek istersiniz? (hemen:30dk)  ")
  adres = input("Adresiniz?  ")
  OrdersDataBase_csv = open ("OrdersDataBase", "w")
  bilgiler = [("Ad:",ad), ("Tc kimlik:",tckimlik), ("Kart:",kart), ("Kart şifresi:",kartşifre), ("Zaman:",zaman), ("Adres:",adres)]

  for name,data in bilgiler:
    OrdersDataBase_csv.write(name+" ")
    OrdersDataBase_csv.write(data+"\n")
    print("\n")
  OrdersDataBase_csv.write(f"{adres} adresine bir tane {tabanistegi} tabanlı ve {sosistegi} malzemeli pizza")
  print("Sipariş Detaylarını görmek için dosyaya bakabilirsiniz...")
  pizza.get_cost() 
  print("ve kartınızdan bu miktar çekilmiştir... Siparişiniz için teşekkürler!")
  print("İşlemi sonlandırmak için x'e basın")
  if input() == "x":
    menu_txt.close()
    OrdersDataBase_csv.close()

  
main()